[project]
name = "ppt-architect"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "openai>=2.21.0",
    "python-pptx>=1.0.2",
    "pyyaml>=6.0.3",
]
